# Generated by Django 4.0.7 on 2022-08-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mls_number', models.CharField(max_length=255)),
                ('property_name', models.CharField(max_length=255)),
                ('agent_name', models.CharField(max_length=255)),
                ('min_notice', models.CharField(max_length=255)),
                ('double_booking', models.CharField(max_length=255)),
                ('appointment_duration', models.CharField(choices=[('1 hour', '1 hour'), ('1/2 Hour', '1/2 Hour'), ('15 minutes', '15 minutes')], max_length=255)),
                ('new_appt', models.CharField(max_length=255)),
                ('denied', models.CharField(max_length=255)),
                ('cancelled', models.CharField(max_length=255)),
                ('confirmed', models.CharField(max_length=255)),
                ('time_change', models.CharField(max_length=255)),
                ('reminder', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
                ('access_instruction', models.CharField(choices=[('door code', 'door code'), ('go direct', 'go direct'), ('key', 'key'), ('sentrilock', 'sentrilock'), ('lock box', 'lock box')], default='key', max_length=125)),
                ('lbx_instruct', models.CharField(max_length=255)),
                ('is_alaram', models.CharField(choices=[('YES_2', 'Yes'), ('NO_2', 'No')], max_length=255)),
                ('alaram_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Form200',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=200)),
                ('broker_street', models.CharField(max_length=200)),
                ('broker_city', models.CharField(max_length=200)),
                ('broker_state', models.CharField(max_length=200)),
                ('broker_zip', models.CharField(max_length=200)),
                ('broker_phone', models.CharField(max_length=200)),
                ('broker_details', models.CharField(max_length=250)),
                ('seller1_name', models.CharField(max_length=200)),
                ('seller1_phone', models.CharField(max_length=200)),
                ('seller2_name', models.CharField(max_length=200)),
                ('seller2_phone', models.CharField(max_length=200)),
                ('spouse_phone', models.CharField(max_length=200)),
                ('list_date', models.CharField(max_length=200)),
                ('expire_date', models.CharField(max_length=200)),
                ('ack_date', models.CharField(max_length=200)),
                ('list_price', models.CharField(max_length=200)),
                ('list_price_in_word', models.CharField(max_length=200)),
                ('commission_percent', models.CharField(max_length=200)),
                ('commission_amount', models.CharField(max_length=200)),
                ('coop_commission_per', models.CharField(max_length=200)),
                ('coop_commission_amount', models.CharField(max_length=200)),
                ('holdover_day', models.CharField(max_length=200)),
                ('txtp_street', models.CharField(max_length=200)),
                ('txtp_unitNumber', models.CharField(max_length=200)),
                ('txtp_city', models.CharField(max_length=200)),
                ('txtp_state', models.CharField(max_length=200)),
                ('txtp_zipcode', models.CharField(max_length=200)),
            ],
        ),
    ]
