# Generated by Django 4.0.7 on 2022-08-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationInstructions',
            new_name='ApplicationIModel',
        ),
    ]
